# Generated by Django 4.2.16 on 2024-12-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=15)),
                ('currency', models.CharField(max_length=15)),
                ('sector', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('asset_type', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=50)),
            ],
        ),
    ]
